#!/usr/bin/env bash

info() { printf '[setup] %s\n' "$*"; }
die() { printf '[setup] error: %s\n' "$*" >&2; exit 2; }

setup_usage() {
  cat <<'EOF'
usage: setup.sh [--phase foundation|shell|wezterm|quake|neovim|all] [--dry-run] [--install-missing]

Phases 0, 1, 2, Windows Phase 3, and Phase 4 are implemented.
EOF
}

setup_detect_platform() {
  local kernel
  kernel=$(uname -s 2>/dev/null || printf unknown)
  case "$kernel" in
    MINGW*|MSYS*|CYGWIN*) printf '%s\n' windows ;;
    Darwin) printf '%s\n' macos ;;
    Linux)
      if [ -r /etc/os-release ] && grep -Eq '^(ID|ID_LIKE)=.*ubuntu' /etc/os-release; then
        printf '%s\n' ubuntu
      else
        printf '%s\n' linux
      fi
      ;;
    *) printf '%s\n' unknown ;;
  esac
}

require_file() {
  [ -r "$1" ] || die "missing required file: $1"
}

require_dir() {
  [ -d "$1" ] || die "missing required directory: $1"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

has_command() {
  command -v "$1" >/dev/null 2>&1
}

windows_command_exists() {
  if command -v "$1" >/dev/null 2>&1; then
    return 0
  fi
  if command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe -NoProfile -Command "if (Get-Command '$1' -ErrorAction SilentlyContinue) { exit 0 } else { exit 1 }" >/dev/null 2>&1
    return $?
  fi
  return 1
}

setup_backup_chezmoi_targets() {
  local timestamp backup_root target relative backup_target
  timestamp=$(date +%Y%m%d-%H%M%S)
  backup_root="$HOME/.workstation-setup-backup/$timestamp"

  for target in "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.config/workstation" "$HOME/.config/wezterm" "$HOME/.config/nvim" "$HOME/.local/bin/workstation-doctor"; do
    [ -e "$target" ] || continue
    relative=${target#/}
    relative=${relative//\//_}
    relative=${relative// /_}
    backup_target="$backup_root/$relative"
    info "backing up $target to $backup_target"
    mkdir -p "$(dirname -- "$backup_target")"
    cp -R "$target" "$backup_target"
  done
}

setup_apply_chezmoi() {
  local repo_root=${1:?repo root required}
  local source_dir="$repo_root/chezmoi"
  local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/workstation"
  require_command chezmoi
  require_dir "$source_dir"
  info "initializing chezmoi source: $source_dir"
  chezmoi init --source "$source_dir"
  setup_backup_chezmoi_targets
  info 'applying chezmoi dotfiles with --force'
  chezmoi --source "$source_dir" apply --force
  mkdir -p "$config_dir"
  {
    printf '%s\n' '# Generated by cross-platform-workstation setup. Do not commit machine-local paths.'
    printf "export WORKSTATION_REPO_ROOT='%s'\n" "$repo_root"
  } >"$config_dir/env.sh"
}

setup_validate_interactive_shell() {
  local repo_root=${1:?repo root required}
  info 'validating configured interactive Bash shell'
  (
    cd "$repo_root" || exit 1
    bash -i -c '
      set -e
      export WORKSTATION_REPO_ROOT="$PWD"
      platform-info
      doctor --phase shell
      native_path=$(winpath "$PWD")
      test -n "$native_path"
      unix_path=$(unixpath "$native_path")
      test -n "$unix_path"
      project >/tmp/workstation-project-stub.out 2>&1 && exit 1 || test "$?" -eq 64
      agent >/tmp/workstation-agent-stub.out 2>&1 && exit 1 || test "$?" -eq 64
    '
  )
}
